/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <set>
#include <map>
#include <ctime>
#include <queue>
#include <stack>
#include <deque>
#include <cmath>
#include <string>
#include <vector>
#include <cstdio>
#include <cctype>
#include <bitset>
#include <numeric>
#include <iomanip>
#include <sstream>
#include <fstream>
#include <cstdlib>
#include <cassert>
#include <iostream>
#include <algorithm>
#include <functional>
#include <unordered_map>

using namespace std;

class Task {
public:
    void solveOne() {
        return;
    }

    void solve() {
        int nt = 1;
        //cin >> nt;
        for (int it = 0; it < nt; ++it) {
            solveOne();
        }
        return;
    }
};

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    Task solver;
    solver.solve();
    return 0;
}
